### ISSUE TITLE
IE7/8 Errors

### ISSUE THREAD

**Issue by Integralist** [ded/morpheus#1]
I'm using IE9 'BrowserMode' to jump back to IE7/8 (using Parallels Desktop for Mac).

SCRIPT5009: 'html' is undefined
morpheus.js, line 7 character 7

SCRIPT5009: 'morpheus' is undefined 
ender.js, line 24 character 3

SCRIPT5007: The value of the property 'morpheus' is null or undefined, not a Function object 
ender.js, line 4 character 7

Also, when I strip out Ender and use just Morpheus on it's own I get similar errors.

**Comment by ded** [comment]
it's the getStyle method. this is an easy fix.

**Comment by ded** [comment]
fixed in 1.1.2
