### ISSUE TITLE
border-color doesn't fade, background-color does

### ISSUE THREAD

**Issue by coolaj86** [ded/morpheus#17]
I've got an input validation that I want to turn bright green and then fade out to nothing.

```
    function morph(el) {
      morpheus(el, {
          "border-color": "#0FF"
        , "duration": 1000
        , "complete": function () {
            $(el).removeClass('saved')
          }   
      }); 
    }
```

Is there a technical limitation as  to why `border-color` and `background-color` behave differently?

**Comment by ded** [comment]
it works. the readme says when doing color animation that you need to explicitly set the style on it first — and not with a named color (only `#hex` or `rgb()`)

that means, do this first...

``` js
// fade from 0ff -> fff
el.style.borderColor = '#0ff'
morpheus(el, {
  'border-color': '#fff'
  ...
})
```
