### ISSUE TITLE
line-height units should not be ignored

### ISSUE THREAD

**Issue by mantoni** [ded/morpheus#20]
If `lineHeight` is specified with `px`, morpheus animates it without the unit which is interpreted as `em`.

``` javascript
morpheus($nodes, {
  lineHeight: "21px"
});
```

Removing `lineHeight` from the `unitless` object fixes the issue for me, but not sure about side effects with other use cases.

**Comment by ded** [comment]
yeah, i can't remove it, but we just need a special case around it since it's the _ONE AND ONLY_ property that can accept a unit, and also not (jerk css gods). will see what we can do
