### ISSUE TITLE
Weird nodes opacity modification

### ISSUE THREAD

**Issue by pyrsmk** [ded/morpheus#21]
Hi ;)

I don't understand _at all_ what happens with my slideshow. Take a look by yourself [here](http://home.dreamysource.fr/dreamysource.fr/dev).

It seems morpheus modifies next slides properties although I don't tell it to do that. It also appears that some nodes are never hidden.

I've got the latest morpheus version. It's integrated in an experimental ender-like framework of my own. Anyway, I've tested to know where those weird bugs come from: good nodes are passed to morpheus.

If I don't use morpheus correctly, please tell me :)

PS: the non-minified version of quark is placed at http://home.dreamysource.fr/dreamysource.fr/dev/js/quark.js

**Comment by ded** [comment]
will have a look

**Comment by ded** [comment]
where are you calling `animate()`?

**Comment by pyrsmk** [comment]
I call `fadeIn()` and `fadeOut()` in script.js, into the `slideshow()` closure, at the top of the script.

**Comment by pyrsmk** [comment]
I've just found a bug in my linker js file for morpheus. I close this thread for now, maybe the opacity bug is then resolved ;)
