### ISSUE TITLE
Use CSS transitions if available

### ISSUE THREAD

**Issue by bengourley** [ded/morpheus#29]
It would be really good if morpheus would use CSS transitions if available. I imagine you thought about this and went with `requestAnimationFrame` instead, but aren't CSS transitions more performant? Why did you decide against it?

**Comment by ded** [comment]
css transitions can be easily done by swapping classnames and letting css handle it. nevertheless, contrary to popular belief, css transitions are not hardware-accelerated (altho transforms are). not to mention, the `requestAnimationFrame` method is receiving more and more development attention and makes more sense for the future of JS animating
