### ISSUE TITLE
IE7 Script Error (Invalid Property Value)

### ISSUE THREAD

**Issue by Integralist** [ded/morpheus#4]
Running IE7 via Parallel Desktop (Document Mode: IE7 Standards).

The 'integration.html' example provided errors...

Invalid property value.  morpheus.js, line 163 character 11
Invalid property value.  morpheus.js, line 163 character 11

```
ie && k == 'opacity' ?
```

**Comment by gblazex** [comment]
The problem is actually one line below that. Characters cannot be accessed via `str[index]` in IE6-7. It's only been introduced in ES 5 (altough some browsers have been supporting it for a while).

https://github.com/ded/morpheus/pull/5
