### ISSUE TITLE
iOS6: complete calls

### ISSUE THREAD

**Issue by zwise** [ded/morpheus#41]
Have you heard of or seen any problems with the `complete` calls for iOS6?  I'm seeing a problem where the callbacks never fire until I reposition the browser window (i.e. scrolling).  This issue doesn't happen in any other browsers I've tested.

**Comment by ded** [comment]
hmmm... i'll have to try it out...

**Comment by ded** [comment]
they're working for me here: http://ded.github.com/morpheus/

tried it on iOS6 — both Safari and Chrome

**Comment by zwise** [comment]
thanks for looking into this @ded.  I must have some conflicting packages or something else getting in the way.  I'll do some more debugging on my end.
