### ISSUE TITLE
opacity misspelled as opasity

### ISSUE THREAD

**Issue by micmath** [ded/morpheus#44]
Inner function has misspelled name: "opasity".

https://github.com/ded/morpheus/blob/master/src/morpheus.js#L35

**Comment by micmath** [comment]
I can't tell from the no comments why this was closed. Is there a reason?

**Comment by ded** [comment]
this was closed because it's just a variable. i didn't want to conflate it with actual opacity

**Comment by micmath** [comment]
If that is your purpose, why not use a name like `opacitySupported`, making it a bit more self-documenting?
