### ISSUE TITLE
Doesn't work with ems

### ISSUE THREAD

**Issue by pyrsmk** [ded/morpheus#6]
All is in the title :) I can't do animations based on ems and it's very important for responsive designs.

**Comment by ded** [comment]
sounds reasonable. i'll see what i can do.

**Comment by ded** [comment]
in the meantime - technically you _can_ do tweens based on 'em' by using the generic tweener...

``` js
var el = document.getElementById('foo')
morpheus.tween(1000, function (pos) {
  el.style.fontSize = pos + 'em';
}, null, 100, 200);
```

**Comment by pyrsmk** [comment]
You're right, meanwhile I'll use tweens.

**Comment by pyrsmk** [comment]
Bizarrely, morpheus.tween is undefined.

**Comment by ded** [comment]
0.1.6 fixes the morpheus.tween

**Comment by pyrsmk** [comment]
Woh, really quick, thanks :)

**Comment by ded** [comment]
@pyrsmk — fyi: Morpheus has been updated to work with any CSS unit now. Check back on the main readme and see usage notes.

**Comment by pyrsmk** [comment]
Currently I can't test morpheus totally with ems. But with IE8 (in IETester), it returns me an "invalid call or argument" error.

**Comment by ded** [comment]
I'll have a look in the morning

**Comment by ded** [comment]
@pyrsmk - i'm not getting that issue. I have it working successfully in IE7,8,9 in native IE's. did you read the usage notes and make sure you're doing it right?

**Comment by pyrsmk** [comment]
I've no native IE but IETester ones. It means they are more chillies than the natives. My only native versions are IE9 and IE10, which work perfectly with morpheus ;)

**Comment by ded** [comment]
It's also working in IETester for me in IE6/7/8/9 (even 'em') — what does your code look like?

**Comment by pyrsmk** [comment]
It doesn't return me this anymore... Maybe it cames from another library... Respond I think. Sorry for the annoyance ;)
